jobs:
  Job1:
    name: Job 1
    steps:
      - type: script
        name: Restore
        working-directory: .
        script-content: dotnet restore PaymentTransactions.sln
      - type: script
        name: Build
        working-directory: .
        script-content: dotnet build --configuration Release
      - type: script
        name: Publish
        working-directory: .
        script-content: dotnet publish -c Release -o ./publish
    runs-on:
      self-hosted:
        - requirement: exists
          name: .NET SDK Exists
          parameter: DotNetCLI
        - requirement: equals
          name: Run on MyAgent
          parameter: teamcity.agent.name
          value: MyAgent
  Job1clone:
    name: Job 1 clone
    steps:
      - type: script
        name: Restore
        working-directory: .
        script-content: dotnet restore PaymentTransactions.sln
      - type: script
        name: Build
        working-directory: .
        script-content: dotnet build --configuration Release
      - type: script
        name: Publish
        working-directory: .
        script-content: dotnet publish -c Release -o ./publish
    runs-on:
      self-hosted:
        - requirement: exists
          name: .NET SDK Exists
          parameter: DotNetCLI
        - requirement: equals
          name: Run on MyAgent
          parameter: teamcity.agent.name
          value: MyAgent
